version: "3"
services:
  prometheus:
    image: gboie/opencloudcx-prometheus
    container_name: prometheus
    ports:
      - 9090:9090

  grafana:
    image: gboie/opencloudcx-grafana
    container_name: grafana
    ports:
      - 3000:3000

  jenkins:
    image: gboie/opencloudcx-jenkins
    container_name: jenkins
    ports:
      - "8000:8080"
      - "5000:5000"
      - "50000:50000"

  sonarqube:
    image: gboie/opencloudcx-sonarqube
    container_name: sonarqube
    ports:
      - "9001:9000"
networks:
  default: