version: "3"
services:
  prometheus:
    image: opencloudcx/opencloudcx-prometheus
    container_name: prometheus
    ports:
      - 9090:9090

  grafana:
    image: opencloudcx/opencloudcx-grafana
    container_name: grafana
    ports:
      - 3000:3000

networks:
  default: