global:
scrape_configs:
- job_name: Prometheus
  static_configs:
    - targets: ["localhost:9090"]
- job_name: 'jenkins'
  metrics_path: '/prometheus/'
  static_configs:
    - targets: ['jenkins:8000']
- job_name: 'sonarqube'
  metrics_path: '/api/prometheus/metrics'
  static_configs:
    - targets: ['sonarqube:9001']