{
 "title": "SonarQube",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "projectName", "label": "Project Name", "query": "label_values(sonar_bugs, name)" }
  ]
 },
 "panels": [
  { "title": "$projectName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "projectName" },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_bugs{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_vulnerabilities{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_code_smells{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_sqale_index{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{name=\"$projectName\"}"
    }
   ]
  }
 ]
}