apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarqube
  name: sonarqube
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 9000
  selector:
    io.kompose.service: sonarqube
status:
  loadBalancer: {}
